version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./resources/db-migrations:/docker-entrypoint-initdb.d/
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    container_name: "redis_docker"
    image: redis:latest
    ports:
      - "6379:6379"

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "localhost"   # this forces single-node mode

    volumes:
      - ./weaviate_data:/var/lib/weaviate
    restart: unless-stopped

volumes:
  mysql-data:
  weaviate_data:

############################## OLD BUT GOLD - WITHOUT WEAVIATE ######################

#version: "3.9"
#services:
#  db:
#    image: mysql:8.0
#    environment:
#      - MYSQL_DATABASE=main
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password
#      - MYSQL_ROOT_PASSWORD=root
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./resources/db-migrations:/docker-entrypoint-initdb.d/
#    command: --default-authentication-plugin=mysql_native_password
#  redis:
#    container_name: "redis_docker"
#    image: redis:latest
#    ports:
#      - "6379:6379"
#volumes:
#  mysql-data: